export enum RunStatus {
  PENDING = "pending",
  IN_PROGRESS = "in_progress",
  INGESTED = "ingested",
  COMPLETED = "completed",
  PUBLISHED = "published",
  FAILED = "failed",
  FADMIN_REGISTERING = "Registering with Fadmin",
  FADMIN_REGISTERING_FAILED = "Registering with Fadmin failed",
  FADMIN_REGISTERED = "Registered with Fadmin",
  DATA_AGGREGATING = "Aggregating data",
  DATA_AGGREGATION_FAILED = "Data aggregation failed",
  DATA_AGGREGATED = "Data aggregated, ready to compile",
  BLUEPRINT_GENERATING = "Generating blueprints",
  BLUEPRINT_GENERATING_FAILED = "Generating blueprints failed",
  BLUEPRINT_GENERATED = "Blueprints generated",
  SFML_GENERATING = "Generating SFML",
  SFML_GENERATING_FAILED = "Generating SFML failed",
  SFML_READY = "SFML ready",
  QC_COMPLETE = "QC complete",
  PUBLISHING = "Publishing",
  PUBLISHING_FAILED = "Publishing failed",
  LIVE = "Run live"
}
